/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as ApiTranscribeFileRouteImport } from './routes/api.transcribe-file'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicChapaWebhookRouteImport } from './routes/api.public.chapa-webhook'
import { Route as AppTranscriptionIdRouteImport } from './routes/_app.transcription.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeFileRoute = ApiTranscribeFileRouteImport.update({
  id: '/api/transcribe-file',
  path: '/api/transcribe-file',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicChapaWebhookRoute = ApiPublicChapaWebhookRouteImport.update({
  id: '/api/public/chapa-webhook',
  path: '/api/public/chapa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTranscriptionIdRoute = AppTranscriptionIdRouteImport.update({
  id: '/transcription/$id',
  path: '/transcription/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/settings': typeof AppSettingsRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/transcription/$id': typeof AppTranscriptionIdRoute
  '/api/public/chapa-webhook': typeof ApiPublicChapaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/settings': typeof AppSettingsRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/transcription/$id': typeof AppTranscriptionIdRoute
  '/api/public/chapa-webhook': typeof ApiPublicChapaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_app/transcription/$id': typeof AppTranscriptionIdRoute
  '/api/public/chapa-webhook': typeof ApiPublicChapaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/admin'
    | '/dashboard'
    | '/pricing'
    | '/settings'
    | '/api/transcribe-file'
    | '/payment/success'
    | '/transcription/$id'
    | '/api/public/chapa-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/admin'
    | '/dashboard'
    | '/pricing'
    | '/settings'
    | '/api/transcribe-file'
    | '/payment/success'
    | '/transcription/$id'
    | '/api/public/chapa-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/pricing'
    | '/_app/settings'
    | '/api/transcribe-file'
    | '/payment/success'
    | '/_app/transcription/$id'
    | '/api/public/chapa-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  ApiTranscribeFileRoute: typeof ApiTranscribeFileRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicChapaWebhookRoute: typeof ApiPublicChapaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-file': {
      id: '/api/transcribe-file'
      path: '/api/transcribe-file'
      fullPath: '/api/transcribe-file'
      preLoaderRoute: typeof ApiTranscribeFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/chapa-webhook': {
      id: '/api/public/chapa-webhook'
      path: '/api/public/chapa-webhook'
      fullPath: '/api/public/chapa-webhook'
      preLoaderRoute: typeof ApiPublicChapaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transcription/$id': {
      id: '/_app/transcription/$id'
      path: '/transcription/$id'
      fullPath: '/transcription/$id'
      preLoaderRoute: typeof AppTranscriptionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTranscriptionIdRoute: typeof AppTranscriptionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTranscriptionIdRoute: AppTranscriptionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  ApiTranscribeFileRoute: ApiTranscribeFileRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicChapaWebhookRoute: ApiPublicChapaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
