/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeFileRouteImport } from './routes/api.transcribe-file'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTranscriptionIdRouteImport } from './routes/_app.transcription.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeFileRoute = ApiTranscribeFileRouteImport.update({
  id: '/api/transcribe-file',
  path: '/api/transcribe-file',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTranscriptionIdRoute = AppTranscriptionIdRouteImport.update({
  id: '/transcription/$id',
  path: '/transcription/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/transcription/$id': typeof AppTranscriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/transcription/$id': typeof AppTranscriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/api/transcribe-file': typeof ApiTranscribeFileRoute
  '/_app/transcription/$id': typeof AppTranscriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/privacy'
    | '/support'
    | '/dashboard'
    | '/api/transcribe-file'
    | '/transcription/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/privacy'
    | '/support'
    | '/dashboard'
    | '/api/transcribe-file'
    | '/transcription/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/docs'
    | '/privacy'
    | '/support'
    | '/_app/dashboard'
    | '/api/transcribe-file'
    | '/_app/transcription/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  ApiTranscribeFileRoute: typeof ApiTranscribeFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-file': {
      id: '/api/transcribe-file'
      path: '/api/transcribe-file'
      fullPath: '/api/transcribe-file'
      preLoaderRoute: typeof ApiTranscribeFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transcription/$id': {
      id: '/_app/transcription/$id'
      path: '/transcription/$id'
      fullPath: '/transcription/$id'
      preLoaderRoute: typeof AppTranscriptionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppTranscriptionIdRoute: typeof AppTranscriptionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppTranscriptionIdRoute: AppTranscriptionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  ApiTranscribeFileRoute: ApiTranscribeFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
